print('\033c')

daily_fact = "\033[35m23 Years ago on 1997 - 2 - 7\n\n\t\033[97mNeXT merges with Apple Computer, starting the path to Mac OS X."

print(f"\t\033[35;1;6m{daily_fact}\033[0m\n")


from dis import dis
import opcode

# When someone tells me


# New Style
asyncio.run(main())

# Old Style
loop = asyncio.get_event_loop()

# except, we are catching an error
# finally, means don't catch the error, but always exit
# What happens to trigger the finally?
try:
    loop.run_until_complete(main())
finally:
    loop.close()
